server:
  port: 8081

spring:
  application:
    name: insurance-request-app
  data:
    mongodb:
      uri: mongodb://localhost:27017/edi_healthcare

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

edi:
  interchange:
    sender-id-qualifier: ZZ
    sender-id: SENDER_ID
    receiver-id-qualifier: ZZ
    receiver-id: RECEIVER_ID
    ack-requested: "0"
    usage-indicator: T
